import java.util.InputMismatchException;
import java.util.Scanner;

public class DivisionEntreCeroConManejoDeExcepciones
{
    public static int quotient(int numerator, int denominator) throws ArithmeticException
    {
        return numerator / denominator;
    }
    
	public static void main(String[] args) {
		Scanner explorer = new Scanner(System.in);
		boolean continueLoop = true;
		do
		{
		try
		{
		System.out.print("Introduce un numerador entero: ");
		int numerator = explorer.nextInt();
		System.out.print("Introduce un denominador entero: ");
		int denominator = explorer.nextInt();
		int operationResult = quotient(numerator,denominator);
		System.out.printf("\nResultado: %d / %d = %d \n", numerator, denominator,operationResult);
		continueLoop = false;
		}
		catch(InputMismatchException inputMismatchException)
		{
		    System.err.printf("\n Excepcion %s \n", inputMismatchException);
		    explorer.nextLine();
		    System.out.println("Debe introducir enteros. Intente de nuevo. \n");
		}
		catch(ArithmeticException arithmeticException)
		{
		    System.err.printf("\nExcepcion %s\n", arithmeticException);
		    System.out.println("Cero es un denominador invalid. Intente de nuevo.\n");
		}
		}while(continueLoop);
	}
}
